site_name: Practical Python For Scientists

repo_name: RMCrean/practical-python-for-scientists
repo_url: https://github.com/RMCrean/practical-python-for-scientists

theme:
  name: material
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - announce.dismiss
    - navigation.tabs
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode    
      primary: teal
      accent: lime
plugins:
- search
- mkdocs-jupyter:
    ignore_h1_titles: True
- mkdocstrings:
    handlers:
      python:
        selection:
          docstring_style: numpy

nav:
  - Course Overview: index.md

  - Day 1:
    - Introduction: day1/day1_intro.md
    - Virtual Enviroments: day1/virtual_enviroments.md
    - Integrated Development Environments and Jupyter Notebooks: day1/ides_jupyter.md
    - Git and GitHub: day1/git_and_github.md
    - Project Structure: day1/project_structure.md
    - Warm Up Exercises: day1/exercises/warm_up_exercises.ipynb
    - Useful Python Functionality: day1/useful_python_functionality.md
    - Apply what you've leaned: day1/exercises/exercise_python_functionality.ipynb 
    - End of Day Overview: day1/day1_end.md
  - Day 2:
    - Introduction: day2/day2_intro.md
    - Variable Naming: day2/variable_naming.md
    - Writing Cleaner Code: day2/cleaner_code.md
    - Exercise, Clean Code: day2/exercises/improve_code_exercise.ipynb 
    - Errors, Warnings, Bugs: day2/errors_warnings_bugs.md
    - Exercise, Errors: day2/errors_bugs_exercise.ipynb
    - End of Day Overview: day2/day2_end.md
  - Day 3:
    - Introduction: day3/day3_intro.md
    - Command Line Options with argparser: day3/arg_passer.md
    - Regular Expressions: day3/regex.md
    - End of Day Overview: day4/day4_end.md
  - Day 4:
    - Introduction: day4/day4_intro.md
    - End of Day Overview: day4/day4_end.md
  - Day 5:
    - Introduction: day5/day5_intro.md
    - End of Day Overview: day5/day5_end.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list